// Editorial planning estimates in minutes: edited min/max, recording min/max.
// Recording includes commentary, scenes, setup, and some retries; excludes grinding.
const EPISODE_TIMES = [
  [30,35,45,65], [30,35,45,70], [25,30,30,45], [30,35,50,75],
  [30,35,45,65], [30,35,55,80], [30,35,45,65], [30,35,45,70],
  [28,33,40,60], [30,35,45,65], [30,35,50,75], [30,35,45,70],
  [30,35,45,70], [30,35,45,65], [30,35,50,75], [30,35,60,90],
  [30,35,50,80], [28,33,40,60], [28,35,40,75], [30,35,50,75],
  [28,33,40,60], [30,35,45,70], [28,33,40,60], [30,35,45,70],
  [30,35,45,70], [25,30,30,45], [30,35,55,90], [30,35,50,85],
  [30,35,55,85], [30,35,60,90], [25,30,40,75], [30,35,60,100],
  [25,35,45,120], [30,35,45,75], [28,33,35,55], [30,35,45,90],
  [30,35,60,120], [25,35,60,120], [30,35,75,150], [25,35,60,120],
  [30,35,75,150], [25,35,60,120], [30,35,90,180], [30,35,60,150],
  [30,35,90,240]
];

// The full 45-part recording roadmap. Episode boundaries are editorial targets.
const ORIGINAL_EPISODES = [
  [1, 'Roxas and the Stolen Summer', 'Simulated Twilight Town', ['Introduce Roxas, Hayner, Pence, and Olette; investigate the stolen photographs.', 'Cover the summer jobs and strange interruptions.', 'Follow the mysterious girl into the Station of Awakening.'], 'Seifer’s introductory duel, Dusks, and Twilight Thorn. Highlight targeting, defensive timing, and reaction commands. Roxas has no Drive Forms.', 'The opening of Day 4, before the Struggle tournament. Preserve your existing recording boundary if different.'],
  [2, 'The Struggle Tournament and Axel', 'Simulated Twilight Town', ['Play the Struggle tournament and retain its supernatural interruption.', 'Introduce Axel and his unexplained connection to Roxas.', 'Investigate the Seven Wonders through the end of Day 5.'], 'Hayner, Vivi, Axel’s first battle, Setzer, and the investigation encounters. Explain Struggle’s orb scoring and Guard against Axel’s approaches.', 'The Day 6 opening transition, before proceeding toward the mansion.'],
  [3, 'Roxas’s Last Summer Day', 'Simulated Twilight Town · Old Mansion', ['Cross the woods and explore the White Room, Library, and basement.', 'Keep Naminé’s explanation, DiZ’s intervention, and the confrontation with the simulation.', 'Follow the final corridor to the sleeping Sora.'], 'Mansion Nobodies and Axel’s second battle. Showcase Roxas’s temporary dual wielding and reaction commands.', 'The transition from Roxas’s farewell into Sora’s awakening.'],
  [4, 'Sora Awakens and the Journey Begins', 'Twilight Town → Mysterious Tower → Hollow Bastion', ['Reunite the party, visit town, and depart by train.', 'Meet Yen Sid, receive the new clothes, and introduce Valor Form.', 'Meet the Restoration Committee and complete the opening defense with Leon.'], 'Station Nobodies, tower Heartless, and the Bailey gate defense. Introduce Valor’s physical strengths and lack of magic.', 'World Map after Hollow Bastion’s introductory route-opening sequence, ready for Land of Dragons.'],
  [5, 'Mulan and the Battle for China', 'Land of Dragons', ['Meet Ping and Mushu at the Encampment; complete Shang’s three assignments.', 'Ascend the Mountain Trail, investigate the cave, and cover the village disaster.', 'Follow Mulan’s revelation into the defense of the Emperor at Imperial Square.'], 'Morale missions, cave ambush, mountain swarm, and Shan-Yu with Hayabusa. Protect the palace gate before chasing damage. Use Valor when party composition permits.', 'World Map immediately after the first visit’s closing scenes.'],
  [6, 'The Beast Behind the Curse', 'Beast’s Castle → Hollow Bastion', ['Meet Belle, move the Wardrobe, and rescue the servants from the Dungeon.', 'Complete the Secret Passage lantern sequence and confront Beast in the West Wing.', 'Return to the Ballroom to rescue Belle; keep the subsequent summons to Hollow Bastion.'], 'Thresholder/Possessor, Beast, Shadow Stalker, and Dark Thorn. Use reaction commands to expose enemies; introduce Cure after the finale.', 'Merlin’s House save point, after the return to Hollow Bastion and before entering Pooh’s book.'],
  [7, 'Into Hades’ Underworld', 'Hollow Bastion → Olympus Coliseum', ['Complete Pooh’s introductory visit and the Heartless book theft; obtain Chicken Little.', 'Meet Meg and descend through the Cave of the Dead toward Hades’ Chamber.', 'Join Auron, survive the escape, and return to the surface.'], 'Book-theft Heartless, the unwinnable Hades confrontation and escape, and Cerberus. Explain the initial Underworld Drive restriction and Auron’s assistance.', 'Coliseum: Vestibule save point, after Cerberus and the surface introduction.'],
  [8, 'Demyx, Pete, and the Hydra', 'Olympus Coliseum', ['Complete Phil’s required training and pursue the Olympus Stone.', 'Cross the Underworld Caverns, rescue Meg, and resolve the Lock confrontation.', 'Return to the devastated Coliseum for the finale.'], 'Demyx’s timed water clones, Pete, and Hydra. Distinguish this encounter from Demyx’s later full fight. Highlight Phil and Pegasus reaction commands.', 'Underworld Entrance save point, after the Hydra resolution.'],
  [9, 'Disney Castle Goes Black and White', 'Disney Castle → Timeless River', ['Visit the Library and collect Torn Page 1.', 'Escort Minnie through the Audience Chamber; investigate the Hall of the Cornerstone.', 'Fetch Merlin from Hollow Bastion, enter the past, and confront the original Pete.', 'Clear the Building Site and Lilliput window scenarios.'], 'Minnie’s escort battles, Past Pete, and the first two window defenses. Demonstrate Faith and careful target selection around protected objectives.', 'Cornerstone Hill save point, with two window scenarios complete.'],
  [10, 'Pete vs. Pete', 'Timeless River → Olympus Coliseum', ['Finish Scene of the Fire and Mickey’s House.', 'Recover the Cornerstone through the waterway chase and settle the two Petes’ conflict.', 'Receive Wisdom Form and complete the Pain and Panic Cup.'], 'Window defenses, Pete’s steamboat, Present Pete, and all ten Pain and Panic rounds, ending with Leon and Yuffie. Introduce Wisdom after acquisition and use party Limits in the cup.', 'Underworld Entrance save point, after collecting the cup reward.'],
  [11, 'Pirates of the Cursed Moon', 'Port Royal', ['Meet Will and Jack at the Rampart and Harbor; establish the moonlight mechanic.', 'Sail to Isla de Muerta and follow the rescue attempt.', 'Defend the Interceptor, clear the gunpowder emergency, and return for the finale.', 'Note Larxene’s portal for the postgame visit.'], 'Cursed pirates, ship defenses, and Barbossa with the Illuminator. Keep pirates in moonlight and restore visibility when the Illuminator intervenes.', 'World Map after Port Royal’s first story conclusion.'],
  [12, 'Aladdin and the Cave of Wonders', 'Agrabah', ['Follow Iago’s redemption and the search for Jafar’s lamp.', 'Enter the Cave of Wonders, escort Abu through the jewel mechanism, and complete the trials.', 'Return to town for Pete’s attack and Genie’s arrival.'], 'Cave trials, the 50-Heartless battle, and Volcanic Lord and Blizzard Lord. Demonstrate elemental matchups and crowd control.', 'The Peddler’s Shop save point, after the world clear and obtaining Genie.'],
  [13, 'Oogie Boogie Steals Christmas', 'Halloween Town → Christmas Town', ['Follow Jack through the Graveyard and Hinterlands.', 'Meet Santa and pursue Lock, Shock, and Barrel.', 'Resolve the graveyard confrontation and return to the factory for Oogie’s scheme.'], 'Prison Keeper and Oogie Boogie. Explain cage positioning and present-launching reactions. Note Magnet’s acquisition for Atlantica.', 'World Map after the first visit’s closing scene.'],
  [14, 'Simba Returns to Pride Rock', 'Pride Lands', ['Meet Nala and cross the Savannah, Wastelands, and Jungle.', 'Reunite with Simba and collect Torn Page 2 in the Oasis.', 'Return to Pride Rock, protect Timon and Pumbaa, and ascend to Scar.'], 'Shenzi, Banzai, Ed, and Scar. Explain Lion Sora’s movement and lack of human-form Drives; showcase Simba’s Limit.', 'Pride Rock: Stone Hollow save point, after the succession scenes.'],
  [15, 'Kairi’s Trail and Ansem’s Computer', 'Twilight Town → 100 Acre Wood → Hollow Bastion', ['Complete Sora’s middle Twilight Town visit and the Sandlot events; obtain Oathkeeper and Limit Form.', 'Complete Piglet’s House and Rabbit’s House in Pooh’s book.', 'Follow the Restoration Committee’s discovery through the castle and activate Ansem’s computer.'], 'Sandlot Nobodies, castle Heartless, and Pooh minigames. Introduce Limit Form’s recovery potential and use its Limits deliberately.', 'Space Paranoids: Pit Cell save point, after meeting Tron.'],
  [16, 'Tron and the Hostile Program', 'Space Paranoids ↔ Hollow Bastion → Atlantica', ['Restore access with Tron and return for the password and Mickey reunion.', 'Obtain Master Form and collect Stitch’s Ukulele Charm near the computer.', 'Clear the Light Cycle sequence and system objectives, then defeat the security program.', 'Visit Atlantica for the tutorial and first three musical chapters.'], 'Security battles, Light Cycle escape, Hostile Program, and early Atlantica rhythm encounters. Demonstrate Cluster Code and introduce Master Form.', 'Atlantica: Undersea Courtyard save point, after Under the Sea.'],
  [17, 'The Battle of 1,000 Heartless', 'Hollow Bastion', ['Continue the computer-room revelations and town emergency.', 'Defeat the Organization’s obstruction and preserve the Goofy sequence.', 'Fight alongside the Final Fantasy allies; collect Torn Page 3 in Crystal Fissure.', 'Clear the army and retain the Organization’s explanation of its plan.'], 'Demyx’s full battle, allied gauntlets, and 1,000 Heartless. Prioritize clone timers; showcase Rising Sun and Sparkle Ray in the army battle.', 'Automatic World Map transition after the post-battle revelations.'],
  [18, 'The Hooded Stranger and Storm Rider', 'Land of Dragons → Olympus Coliseum', ['Pursue the hooded stranger from village to mountain.', 'Defend the Imperial City and collect Torn Page 4 in the Throne Room.', 'Complete the Cerberus Cup after finishing the world.'], 'Hooded stranger, palace Nobodies, Storm Rider, and ten Cerberus Cup rounds ending with Cerberus. Use aerial openings and demonstrate Drives under time pressure.', 'Underworld Entrance save point, after winning the cup.'],
  [19, 'Xaldin’s Last Dance', 'Beast’s Castle', ['Return for the dance and follow Xaldin’s manipulation.', 'Recover Beast’s resolve and pursue the stolen rose.', 'Keep Belle’s intervention and the confrontation on the Bridge.', 'Mark Marluxia’s portal in Beast’s Room for later.'], 'Ballroom Nobody ambush and Xaldin. Explain Learn/Jump, respect the wind barrier, and prioritize defensive timing.', 'Parlor save point, after closing scenes and world-clear rewards.'],
  [20, 'Luxord’s Curse and the Grim Reaper', 'Port Royal → 100 Acre Wood', ['Investigate Luxord and the renewed curse.', 'Fight the first Grim Reaper, search the shipwrecks, and recover medallions.', 'Collect Peter Pan’s Feather Charm in the Ship Graveyard.', 'Finish the Harbor battle, then complete Kanga’s House in Pooh’s book.'], 'Both Grim Reaper battles, Gamblers, and pirates. Use magic to recover medallions in the second fight; secure Magnera.', 'Merlin’s House save point, after leaving Pooh’s book.'],
  [21, 'Jafar Unleashed', 'Agrabah', ['Investigate the remodeled shop and Jafar’s return.', 'Complete the carpet pursuit and desert ruin mechanisms.', 'Collect Torn Page 5 in the Ruined Chamber and escape.', 'Return to the Palace for the final showdown.'], 'Carpet combat, ruin defenses, and Genie Jafar. Explain vulnerable body sections and reaction punishments. Drives are unavailable during the carpet boss.', 'The Peddler’s Shop save point after Jafar. Show Vexen’s portal as a future objective.'],
  [22, 'The Experiment and Ursula’s Revenge', 'Halloween Town → Atlantica', ['Investigate the missing presents and return to the factory.', 'Capture Lock, Shock, and Barrel; manufacture presents and set the trap.', 'Resolve the Experiment’s story and obtain Decisive Pumpkin.', 'Return to Atlantica for the Magnera-gated Ursula chapter.'], 'Lock, Shock, and Barrel capture encounter, the Experiment, and Ursula’s Revenge. Explain the Experiment’s separated components; Ursula is a rhythm-based boss.', 'Undersea Courtyard save point, after defeating Ursula and receiving Mysterious Abyss.'],
  [23, 'Simba Faces the Groundshaker', 'Pride Lands → 100 Acre Wood', ['Investigate Scar’s image and Simba’s uncertainty.', 'Track the hyenas and help Simba recommit to his role.', 'Defend the Savannah from the giant Heartless.', 'Complete Spooky Cave in Pooh’s book.'], 'Hyena chases and Groundshaker. Showcase evasion, reactions, and the transition onto its back. Obtain Thundaga for Atlantica’s finale.', 'Merlin’s House save point, after the completed Spooky Cave chapter.'],
  [24, 'Auron Breaks Free of Hades', 'Olympus Coliseum', ['Enter the tournament storyline and investigate Auron.', 'Retrieve his controlling statue and return his memories.', 'Resolve Hercules’s crisis and defeat Hades.', 'Clear the newly available Titan Cup.'], 'Story tournament enemies, Hades, and Titan Cup rounds ending with Hercules. Demonstrate aura spheres and Summons under damage-point rules.', 'Underworld Entrance save point, after winning the Titan Cup.'],
  [25, 'Shutdown of the MCP', 'Hollow Bastion → Space Paranoids → Radiant Garden', ['Respond to the computer-controlled Heartless and hostile town defenses.', 'Rejoin Tron and survive the Solar Sailer sequence.', 'Reach the Central Computer and end the MCP’s control.', 'Preserve the revelation of Hollow Bastion’s original name.'], 'Town defense, Solar Sailer waves, Sark, giant Sark, and MCP. Explain Tron’s role in deleting defenses and reserve MP for openings.', 'Merlin’s House save point in Radiant Garden, after the resolution.'],
  [26, 'A Promise to Pooh and Ariel', '100 Acre Wood → Atlantica → Twilight Town', ['Complete Starry Hill, restore Pooh’s memories, and finish the book.', 'Complete A New Day Is Dawning using the Thundaga unlock.', 'Review world completions and show a concise Form/Summon progress report.', 'Demonstrate a short preparation circuit, then stage the return to Twilight Town.'], 'Pooh’s final minigame and Atlantica’s final musical; no conventional boss. Let the emotional world endings supply the climax. Skip score chasing.', 'The Usual Spot save point, before the final mansion investigation.'],
  [27, 'Axel’s Sacrifice and the Roxas Duel', 'Twilight Town → The World That Never Was', ['Investigate the mansion with the Twilight Town friends and activate the computer.', 'Follow the alternate-town connection into Betwixt and Between.', 'Preserve Axel’s final sequence.', 'Cross the Dark City to Memory’s Skyscraper.'], 'Mansion Nobodies, Axel-assisted gauntlet, and Roxas. Use Guard and deliberate punish windows; explain the duel reaction command.', 'The Brink of Despair save point, after Roxas and receiving Two Become One.'],
  [28, 'Xigbar’s Ambush and Luxord’s Gamble', 'The World That Never Was', ['Demonstrate unlocking Final Form after Roxas; use Two Become One and trim repeated attempts.', 'Enter the castle, follow the rescue scenes, and confront Xigbar.', 'Continue through reunions and upper chambers to Luxord.'], 'Castle Nobodies, Xigbar, and Luxord. Return projectiles and respect Xigbar’s barrage. Explain Luxord’s time gauge and command games.', 'Backtrack to Twilight’s View save point after Luxord, before Saïx.'],
  [29, 'Saïx, Xemnas, and the Final Door', 'The World That Never Was → Olympus Coliseum', ['Defeat Saïx and continue through the upper castle revelations.', 'Retain Ansem the Wise’s final sequence and Riku’s restoration.', 'Defeat the first Xemnas battle and open the final door.', 'Leave temporarily to complete the Goddess of Fate Cup.'], 'Saïx, first Xemnas, and Goddess of Fate rounds including Hades. Disrupt Berserk with dropped weapons; explain Xemnas’s building reaction sequence.', 'Return and save at The Altar of Naught, before entering the final door.'],
  [30, 'Xemnas and the Story’s End', 'The World That Never Was', ['Enter the final door with equipment and items prepared.', 'Cover the fortress assault and Sora/Riku partnership.', 'Keep the beach, homecoming, and essential ending scenes; edit credits to fit.', 'Create a completed-game save and reload it.'], 'Fortress objectives, Armored Xemnas, dragon battle, subsequent armored phase, and final Xemnas. Explain Riku’s rescue and both characters’ laser-defense inputs.', 'Reloaded completed save at The Altar of Naught.'],
  [31, 'Zexion and Lexaeus — The Lost Organization', 'Olympus Coliseum → Twilight Town', ['Open the postgame with a short equipment, ability, and level update.', 'Enter Zexion’s portal at Cave of the Dead: Inner Chamber.', 'Defeat Lexaeus through the Sandlot portal.', 'Explain how Silhouette wins unlock their Data rematches.'], 'Absent Silhouette Zexion and Lexaeus. Escape the book dimension and read altered commands; guard Lexaeus and punish retaliation openings.', 'The Usual Spot save point, after both victories.'],
  [32, 'Vexen, Larxene, and Marluxia', 'Agrabah → Port Royal → Beast’s Castle', ['Defeat Vexen through The Peddler’s Shop portal.', 'Sail to Isla de Muerta and enter Larxene’s Rock Face portal.', 'Finish with Marluxia in The Beast’s Room.', 'Confirm all five Silhouettes are cleared.'], 'Absent Silhouette Vexen, Larxene, and Marluxia. Avoid Vexen’s tracking circle, use Reflect against committed attacks, and explain Marluxia’s curse counter.', 'The Beast’s Room save point, after Marluxia.'],
  [33, 'Sephiroth and the One-Winged Showdown', 'Radiant Garden', ['Show the movement-ability build and a brief preparation montage.', 'Challenge Sephiroth at Dark Depths.', 'Report to Cloud, return to Sephiroth, and preserve the Cloud/Tifa resolution.', 'Collect Fenrir and compare its specialized ability to your usual Keyblade.'], 'Sephiroth. Prepare for the opening reaction, interrupt Heartless Angel when possible, and use Limit Form for emergency recovery.', 'Crystal Fissure save point, after the Fenrir reward sequence.'],
  [34, 'The Three Paradox Cups', 'Olympus Coliseum', ['Confirm four ordinary cups and Form/Summon preparation are complete.', 'Speak to Hades and clear Pain and Panic Paradox.', 'Clear Cerberus Paradox, then Titan Paradox.', 'Show Hades Paradox available in the menu.'], 'Thirty rounds across three cups, including Leon and Yuffie, Cerberus, and Hercules. Contrast party Limits, timed Form combat, and Summon survival.', 'Underworld Entrance save point, with the first three Paradox cups cleared.'],
  [35, 'Hades Paradox Cup — The First 30 Rounds', 'Olympus Coliseum · Underdrome', ['Begin at round 1 and clear through round 30.', 'Explain each ten-round rules change as it arrives.', 'Keep named opponents intact; shorten routine waves as needed.'], 'Volcanic Lord, Yuffie and Tifa, Blizzard Lord, Pete, Cloud and Tifa, and Hades at round 30. Use Summons during the damage-point block and party Limits in the next block.', 'After round 30, exit, confirm round 31 is selectable with Hades, then save at Underworld Entrance.'],
  [36, 'Hades Paradox Cup — The Final Trials', 'Olympus Coliseum · Underdrome', ['Resume at round 31.', 'Beat the timed block, then adapt to the final solo block.', 'Finish round 50 and show the reward.'], 'Leon and Cloud at 40; Cerberus at 48; Leon, Cloud, Yuffie, and Tifa at 49; Hades at 50. Use Final Form in the timed section and Limit Form for final-block recovery. No journal score target.', 'Underworld Entrance save point after winning Hades Paradox.'],
  [37, 'Into the Cavern of Remembrance', 'Radiant Garden · Cavern of Remembrance', ['Enter from the Postern with level-3 growth abilities equipped.', 'Traverse Depths, Mineshaft, Mining Area, Engine Chamber, and final Mineshaft.', 'Clear all three Transport to Remembrance Nobody gauntlets.', 'Inspect the Garden of Assemblage portals and open the Restoration Site shortcut.'], 'Enhanced Heartless, movement-gate battles, and three mandatory Nobody gauntlets. Use Magnet and Reflect; use physical attacks against elemental-resistant Sorcerers.', 'Take the Garden shortcut to the Restoration Site, then continue to the Postern save point.'],
  [38, 'Data Xigbar and Luxord', 'Radiant Garden · Garden of Assemblage', ['Establish the Data battle format and thirteen-fight checklist.', 'Defeat Xigbar and explain his upgraded pressure.', 'Switch to Luxord for a contrasting timing-based fight.'], 'Data Xigbar and Data Luxord. Return projectiles, survive the barrage, and practice Luxord’s command selection and final game. Keep useful learning attempts and full wins.', 'Postern save point via the Garden shortcut, with 2/13 Data victories.'],
  [39, 'Data Vexen and Demyx', 'Radiant Garden · Garden of Assemblage', ['Prepare a magic-focused loadout and reliable MP recovery.', 'Defeat Vexen, explaining his tracking circle and Anti-Sora.', 'Reconfigure for Demyx’s clone checks and finish the second battle.'], 'Data Vexen and Data Demyx. Use Fire-based punishment while managing Vexen’s shield and clone. Showcase Wisdom Form Firaga against timed water formations.', 'Postern save point via the Garden shortcut, with 4/13 Data victories.'],
  [40, 'Data Lexaeus and Larxene', 'Radiant Garden · Garden of Assemblage', ['Contrast heavy attacks with rapid multi-directional pressure.', 'Defeat Lexaeus using measured defensive play.', 'Adjust equipment and defeat Larxene; show six victories.'], 'Data Lexaeus and Data Larxene. Respect power escalation and counter opportunities. Let Larxene’s committed attacks create Reflect and combo openings.', 'Postern save point via the Garden shortcut, with 6/13 Data victories.'],
  [41, 'Data Zexion and Marluxia', 'Radiant Garden · Garden of Assemblage', ['Explain both special failure conditions before entering.', 'Defeat Zexion and show recovery inside his book dimension.', 'Defeat Marluxia while tracking the curse counter and floor hazards.', 'Confirm all five Castle Oblivion members’ Data versions are beaten.'], 'Data Zexion and Data Marluxia. Prioritize escape commands and safe positioning; distinguish HP damage from counter loss and use counter-restoring reactions.', 'Postern save point via the Garden shortcut, with 8/13 Data victories.'],
  [42, 'Data Axel and Saïx', 'Radiant Garden · Garden of Assemblage', ['Revisit Axel’s arena with Sora and establish the burning-floor danger.', 'Secure the first victory, then switch to Saïx.', 'Show how the end of an attack sequence creates a safe damage window.'], 'Data Axel and Data Saïx. Use Axel’s reaction sequence to manage the arena and finish correctly. Recover Saïx’s weapon to break Berserk.', 'Postern save point via the Garden shortcut, with 10/13 Data victories.'],
  [43, 'Data Roxas and Xaldin', 'Radiant Garden · Garden of Assemblage', ['Return to Roxas with the complete defensive and movement toolkit.', 'Show one concise adjustment that leads to victory.', 'Close with Xaldin and a callback to Beast’s Castle.', 'Reveal Xemnas as the only remaining Data opponent.'], 'Data Roxas and Data Xaldin. Guard Roxas’s strings without attacking through retaliation. Stock Learn/Jump opportunities and respect Xaldin’s wind attacks.', 'Postern save point via the Garden shortcut, with 12/13 Data victories.'],
  [44, 'Data Xemnas — Organization XIII Defeated', 'Radiant Garden · Garden of Assemblage', ['Present the final Data loadout and equip Riku appropriately.', 'Defeat both stages of the Xemnas rematch.', 'Verify every portal’s victory status and open the reward chest.', 'Collect the Proof of Nonexistence.'], 'Data Xemnas’s first and final forms. Cover the opening curse/building sequence, punish windows, Riku’s rescue, and laser defense.', 'Postern save point after collecting the Proof and confirming 13/13 Data victories.'],
  [45, 'Lingering Will — The Ultimate Finale', 'Disney Castle → Keyblade Graveyard', ['Enter the Hall of the Cornerstone portal and preserve the armor’s introduction.', 'Show concise attack-pattern learning, then the full successful fight.', 'Defeat Lingering Will and collect the Proof of Connection.', 'Close with a victory montage and completed mandatory-boss checklist.'], 'Lingering Will / Terra’s Armor. Bring level-3 movement, Once More, Second Chance, and recovery items. Use controlled combos, respect retaliation and command seals, and reserve Limit Form for recovery.', 'Return to Disney Castle’s Library save point and save after victory. End with the checklist and farewell.']
].map(([id, title, world, objectives, encounters, stop]) => {
  const [editedMin, editedMax, recordingMin, recordingMax] = EPISODE_TIMES[id - 1];
  return {id, title, world, objectives, encounters, stop, timing:{editedMin, editedMax, recordingMin, recordingMax}};
});

const LEGACY_EPISODE_MAP = Object.fromEntries(Array.from({length:45}, (_, i) => {
  const old = i + 1;
  return [old, old <= 31 ? old : old <= 35 ? old - 1 : old - 2];
}));

const BOSSES = [
  ['as-zexion', 'Zexion', 'Absent Silhouettes', 31], ['as-lexaeus', 'Lexaeus', 'Absent Silhouettes', 31], ['as-vexen', 'Vexen', 'Absent Silhouettes', 32], ['as-larxene', 'Larxene', 'Absent Silhouettes', 32], ['as-marluxia', 'Marluxia', 'Absent Silhouettes', 32],
  ['sephiroth', 'Sephiroth', 'Final challenges', 33], ['hades', 'Hades Paradox Cup', 'Final challenges', 36],
  ['data-xigbar', 'Xigbar', 'Data Organization XIII', 38], ['data-luxord', 'Luxord', 'Data Organization XIII', 38], ['data-vexen', 'Vexen', 'Data Organization XIII', 39], ['data-demyx', 'Demyx', 'Data Organization XIII', 39], ['data-lexaeus', 'Lexaeus', 'Data Organization XIII', 40], ['data-larxene', 'Larxene', 'Data Organization XIII', 40], ['data-zexion', 'Zexion', 'Data Organization XIII', 41], ['data-marluxia', 'Marluxia', 'Data Organization XIII', 41], ['data-axel', 'Axel', 'Data Organization XIII', 42], ['data-saix', 'Saïx', 'Data Organization XIII', 42], ['data-roxas', 'Roxas', 'Data Organization XIII', 43], ['data-xaldin', 'Xaldin', 'Data Organization XIII', 43], ['data-xemnas', 'Xemnas', 'Data Organization XIII', 44], ['lingering-will', 'Lingering Will', 'Final challenges', 45]
].map(([id, name, group, episode]) => ({id, name, group, episode: LEGACY_EPISODE_MAP[episode]}));
