'use strict';
// Compact authoring rows: title, location, story beats, encounters, stopping point,
// estimated edited minutes. The exported dataset uses the canonical Episode keys.
const FF9_EPISODES = [
  ['A Princess, a Play, and a Kidnapping', 'Alexandria / Prima Vista',
    ['Introduce Zidane aboard the Prima Vista; complete the opening crew battle and kidnapping briefing.', 'Follow Vivi through Alexandria to the ticket booth, alley, rooftops, and bell tower; keep the opening character scenes.', 'Perform the stage duel, follow Garnet through the castle, and play Steiner’s search.', 'Finish the escape aboard the airship and keep the crash cinematic.'],
    ['Masked Man (Baku): demonstrate Attack and a few Steal attempts without farming.', 'Steiner encounters and the Bomb-backed escape fight: concentrate damage on Steiner and preserve the scripted escalation.'],
    'At Mosco beside the crashed Prima Vista in Evil Forest, after the crash scenes; save before pursuing Garnet.', [55,80]],
  ['Escape from the Evil Forest', 'Evil Forest',
    ['Follow the forest path and rescue Garnet and Vivi from the plant encounters.', 'Return to the wreck, speak to the party, challenge Baku, and recruit the rescue team.', 'Cross the forest to the spring; recover before the final plant fight.', 'Keep Blank’s rescue, petrification, and the camp conversation.'],
    ['Prison Cage encounters: avoid hurting the captive with careless targeting.', 'Baku duel; Plant Brain; Plant Spider escape battles. Use Vivi’s Fire and Steiner’s Sword Magic; heal before the escape.'],
    'Mist Continent world map after the forest escape and moogle tutorial; summon Moguo and save outside Ice Cavern.', [35,50]],
  ['Through the Ice Cavern', 'Ice Cavern',
    ['Enter from the world map and use Vivi to melt ice blocking the main route.', 'Climb the cavern, keeping party conversations and the blizzard scene.', 'Save at Mois before Zidane separates from the others.', 'Win the solo battle, reunite, and watch Garnet choose the name Dagger.'],
    ['Black Waltz No. 1 and Sealion: remove the mage first; heal Zidane proactively and use Trance if it arrives naturally.'],
    'World map on the Dali side of Ice Cavern; summon Moguo and save before entering Dali.', [30,40]],
  ['Dali’s Hidden Factory', 'Dali village / underground',
    ['Check into the inn and follow the party’s village conversations.', 'Investigate Vivi’s disappearance near the windmill.', 'Descend beneath the village and follow the cargo route through the underground factory.', 'Keep the black mage production reveal; reunite with Vivi and advance to the cargo-loading exit.'],
    ['Underground random battles: show ability learning from equipment and keep Vivi supplied with MP.', 'No required boss in this investigative chapter.'],
    'Pause at the underground cargo-route exit before triggering Black Waltz No. 2. This is an editing boundary; keep recording into Part 5, or retain the earlier village save.', [25,40]],
  ['The Black Waltzes Give Chase', 'Dali / cargo ship',
    ['Resume at the cargo exit and resolve the confrontation with Black Waltz No. 2.', 'Choose to restock in Dali before boarding; save at the inn.', 'Board the cargo ship and explore the deck as Zidane.', 'Keep Vivi’s discovery, the attack on the mages, and the flight through South Gate.'],
    ['Black Waltz No. 2: use physical damage when magical retaliation is a problem.', 'Black Waltz No. 3: exploit Vivi’s scripted Trance while Steiner supports with Sword Magic; heal between attacks.'],
    'Lindblum castle guest room: save at Mogki once the arrival scenes give control.', [30,45]],
  ['Welcome to Lindblum', 'Lindblum castle / city districts',
    ['Meet Regent Cid and retain the explanation of his transformation and the kidnapping plan.', 'Tour the business district, shops, and synthesis counter with a modest story budget.', 'Visit the theater district and Tantalus hideout; keep the party’s available character scenes.', 'Follow Dagger’s song to the castle telescope and prepare for the Festival of the Hunt.'],
    ['No required boss. Compare useful equipment abilities without purchasing every item.', 'Set a Festival loadout and keep recovery items on Zidane.'],
    'Save at Mogki in the castle guest room before starting the Festival of the Hunt.', [30,45]],
  ['The Festival of the Hunt', 'Lindblum / Dragon’s Gate',
    ['Play the Festival once; prioritize an entertaining route through the districts over a perfect score.', 'Show the results and the news from Burmecia.', 'Keep the banquet, Dagger’s departure, and the new party’s decision.', 'Ride the elevator and leave through Dragon’s Gate.'],
    ['Festival monsters; Zaghnol if reached naturally. Let Freya assist and heal instead of resetting for a prize.', 'No additional grinding or festival replay required.'],
    'Save at Moonte at Lindblum’s Dragon’s Gate before crossing the world map.', [30,40]],
  ['Across the Mist Continent', 'Qu’s Marsh / Gizamaluke’s Grotto entrance',
    ['Travel north from Lindblum and stop at Qu’s Marsh to recruit Quina.', 'Use the recruitment to introduce Blue Magic; catch only what the scene needs.', 'Continue toward Gizamaluke’s Grotto and watch the entrance aftermath.', 'Open the initial bell-locked passage and establish the dungeon route.'],
    ['World-map encounters; introductory black mage guards inside the grotto.', 'Quina’s Eat is an introduction, not a Blue Magic collection project.'],
    'Return to the world map outside Gizamaluke’s Grotto and save with Moguo after the opening passage, before the deeper bell route.', [25,35]],
  ['The Fall of Gizamaluke', 'Gizamaluke’s Grotto / South Gate',
    ['Resume the bell puzzle and follow the passages to the moogle couple.', 'Use the Kupo Nut interaction to continue; recover and save before the boss.', 'Defeat the grotto guardian and keep the transition to Steiner and Dagger.', 'Complete the South Gate disguise and checkpoint scenes, then enter the rest area before boarding.'],
    ['Gizamaluke: spread healing duties between items and Quina; avoid letting water damage leave multiple allies critical.', 'Grotto guards and mandatory route encounters. Do not climb into the dangerous optional plateau.'],
    'Save at Grimo in South Gate’s rest area after the checkpoint sequence, before continuing the journey.', [35,50]],
  ['Burmecia in the Rain', 'Burmecia lower city',
    ['Finish the South Gate boarding scenes, return to Zidane’s party, and cross the world map to Burmecia.', 'Explore the ruined streets and houses; keep Freya’s reactions.', 'Cross the collapsing balcony and find the Protection Bell needed to progress.', 'Help the civilians and climb toward the palace approach.'],
    ['Black mage soldiers and city encounters. Use Silence remedies and group healing as needed.', 'Take nearby upgrades but skip the Mimic chest if supplies are low.'],
    'Save with Atla in Burmecia’s palace-area shelter before approaching the royal courtyard.', [30,40]],
  ['Beatrix and the End of Disc One', 'Burmecia palace',
    ['Resume from Atla, recover, and check current equipment abilities.', 'Finish the palace approach and hear the confrontation with Brahne and Kuja.', 'Play the first Beatrix encounter through its scripted conclusion.', 'Keep the entire closing sequence and mark the Disc 1 boundary.'],
    ['Beatrix I: this is a scripted defeat, not a failed run. Heal to stay in the encounter; do not reset for rare steals.'],
    'Use the end-of-disc save prompt where available. On continuous editions, stop at the transition to Dagger and Steiner at Summit Station.', [15,25]],
  ['Dagger’s Road to Treno', 'South Gate / Summit Station / Treno',
    ['Resume Dagger and Steiner at Summit Station and reunite with Marcus.', 'Ride the cable car and resolve the attack on the journey.', 'Travel through South Gate toward Treno; bypass optional Dali backtracking.', 'Enter Treno and follow the party split and opening city scenes.'],
    ['Damaged Black Waltz No. 3: keep Dagger healing while Steiner and Marcus attack.', 'World-map encounters; avoid expensive auction diversions.'],
    'Save with Mogrich outside Treno’s weapon shop before advancing the Supersoft search.', [30,40]],
  ['Supersoft and the Gargan', 'Treno / Gargan Roo',
    ['Follow Marcus’s Supersoft investigation and the meeting with Baku.', 'Visit Doctor Tot’s tower and keep Dagger’s memories.', 'Descend into Gargan Roo, activate the switches, and prepare the gargant route.', 'Ride toward Alexandria and keep the party’s capture.'],
    ['Ralvurahva: protect Dagger’s MP and use Steiner and Marcus for steady damage.', 'Gargan Roo route encounters; save with Mochos before departure.'],
    'At the story transition back to Zidane’s group after the capture. Continue until control returns on the world map and save with Moguo outside Cleyra.', [35,50]],
  ['Climbing to Cleyra', 'Cleyra’s Trunk / settlement',
    ['Enter the trunk, route the sand switches, and climb the interior paths.', 'Save during the climb and proceed to the settlement tour.', 'Follow the call to the sandpit and protect Puck.', 'Keep the settlement conversations and Freya’s ceremonial sequence.'],
    ['Antlion: restore HP after Sandstorm; avoid attacking recklessly into counters.', 'Trunk enemies and quicksand navigation.'],
    'Save with Mopli in Cleyra’s inn before starting the siege sequence.', [35,50]],
  ['The Siege of Cleyra', 'Cleyra / Red Rose',
    ['Defend the settlement and direct fleeing residents toward safety.', 'Keep Fratley’s appearance and Freya’s reunion scene.', 'Face Beatrix, then follow the party onto the Red Rose.', 'Watch the full Odin cinematic and the overheard plan for Dagger.'],
    ['Alexandrian soldiers and black mages; conserve resources between defense waves.', 'Beatrix II: survive the scripted fight and accept its ending.'],
    'Save with Serino aboard the Red Rose before using the teleport route to Alexandria.', [35,50]],
  ['Rescue from Alexandria Castle', 'Alexandria castle / underground chapel',
    ['Escape the cage as Steiner and Marcus and reconnect with Zidane’s group.', 'Follow the timed castle rescue route directly to Dagger.', 'Defeat the court jesters and carry Dagger out.', 'Keep Beatrix’s change of allegiance and the divided escape parties.'],
    ['Zorn and Thorn: interrupt the twin holding the charged attack.', 'Beatrix III and scripted conclusion; Bandersnatch escape fights with the supporting parties.'],
    'Save with Mosh in the underground chapel when the rescue sequence allows, before the final gargant escape leg.', [40,60]],
  ['Ramuh’s Story at Pinnacle Rocks', 'Alexandria escape / Pinnacle Rocks',
    ['Finish the underground escape and board the gargant.', 'Resolve the pursuit and arrive at Pinnacle Rocks.', 'Locate Ramuh’s story fragments and assemble the tale for Dagger.', 'Keep the view of Lindblum’s destruction and descend toward the city.'],
    ['Ralvuimago: stop striking when it curls into its defensive posture; use the opening to heal.', 'Ramuh’s dialogue trial; no optional boss.'],
    'Save with Monty at Pinnacle Rocks before leaving for Lindblum, after completing Ramuh’s trial.', [30,45]],
  ['Lindblum’s Ruins and Fossil Roo', 'Lindblum / Qu’s Marsh / Fossil Roo',
    ['Enter ruined Lindblum, speak with Cid, and replenish supplies.', 'Return through Qu’s Marsh; let Quina reveal the route to Fossil Roo.', 'Complete the Armodullahan chase and confront Lani.', 'Navigate the gargant switch network to the Outer Continent; omit excavation grinding.'],
    ['Armodullahan: prioritize escaping the chase instead of treating it as a farming target.', 'Lani: watch Dagger’s health and use the other characters to maintain pressure.'],
    'On the Outer Continent world map after Fossil Roo’s exit, summon Moguo and save.', [55,80]],
  ['The Village Beyond the Forest', 'Conde Petie / Black Mage Village',
    ['Enter Conde Petie, shop selectively, and follow the report of a black mage.', 'Cross the world map to the forest and follow the path that leads to the hidden village.', 'Explore the village and retain Vivi’s conversations about life and death.', 'Rest, then return toward Conde Petie for the mountain passage.'],
    ['World-map encounters only; this episode’s climax is Vivi’s story.', 'Purchase useful magic-teaching equipment without pursuing a complete inventory.'],
    'Save with Mogryo in Black Mage Village after the overnight scenes, before returning to Conde Petie.', [30,45]],
  ['Eiko and the Lost Summoners', 'Conde Petie mountain path / Madain Sari',
    ['Complete the marriage ceremony needed to pass Conde Petie’s gate.', 'Meet Eiko on the mountain path and follow her toward home.', 'Cross the path and defeat the giant blocking progress.', 'Tour Madain Sari, keep Eiko’s cooking and dinner scenes, and visit the Eidolon Wall.'],
    ['Hilgigars: heal after Earthquake and avoid dragging the fight out for the rare flute steal.', 'Mountain enemies; take obvious route treasures only.'],
    'After Madain Sari’s overnight scenes, leave to the world map and save with Moguo before heading to Iifa.', [45,65]],
  ['The Truth Beneath the Iifa Tree', 'Iifa Tree interior',
    ['Let Eiko open the seal at the tree’s entrance.', 'Descend through the roots and living lift; keep Vivi’s questions.', 'Follow the interior route to the source of Mist.', 'Keep the confrontation and the aftermath of the Mist clearing.'],
    ['Undead route battles and Soulcage. Conventional healing and damage give the fight room to breathe; explain the undead healing vulnerability only if you choose to use it.'],
    'Exit Iifa after the Mist-clearing scenes and save with Moguo on the world map before returning to Madain Sari.', [35,50]],
  ['The Scarlet-Haired Stranger', 'Madain Sari',
    ['Return to Eiko’s village and investigate the stolen stone.', 'Follow the hostage confrontation and Zidane’s decision to fight alone.', 'Keep the boat conversation and Dagger’s returning memories.', 'Welcome Amarant and choose the party for the return to Iifa.'],
    ['Scarlet Hair / Amarant: attack when he approaches; use the quiet stretches to heal Zidane.', 'No optional collection detours.'],
    'World map outside Madain Sari after Amarant joins; save with Moguo.', [30,45]],
  ['Brahne’s Last Battle', 'Iifa Tree / coast',
    ['Return to Iifa and climb toward Kuja’s position.', 'Keep the confrontation and the fleet’s arrival.', 'Defend against the mandatory Mistodon battles while the larger battle unfolds.', 'Watch Bahamut, the Invincible, and Brahne’s final scenes in full.'],
    ['Mistodon story battles: keep a healer active and avoid wasting consumables on optional encounters.', 'Kuja is a cinematic presence here, not a playable boss fight.'],
    'End-of-Disc-2 save prompt where available; otherwise the transition to Alexandria at the start of Disc 3.', [30,45]],
  ['A Coronation and a Card Tournament', 'Alexandria / Treno',
    ['Keep the coronation preparations, Vivi’s city scenes, and Eiko’s letter sequence.', 'Follow the party to Treno through the story route.', 'Play the required Tetra Master tournament rounds; retain the Oglop opponent reveal.', 'Advance the event that interrupts the celebrations.'],
    ['Required tournament games only: explain arrows briefly and accept imperfect outcomes.', 'Skip card collecting, auction loops, and optional Treno monsters.'],
    'At the transition from Treno to the attack on Alexandria after the tournament. Keep recording into Part 25; preserve the earlier Treno save.', [50,75]],
  ['Alexander Awakens', 'Alexandria castle',
    ['Assign the Knights of Pluto their defense duties as Dagger.', 'Fight through the streets with Steiner and Beatrix.', 'Guide Dagger and Eiko to the summoning sequence; reunite the rescue party.', 'Keep the full Alexander, Bahamut, and Invincible cinematics and the retreat.'],
    ['Mistodon defense battles; use Beatrix’s support to keep Steiner standing.', 'Tantarian is omitted; Alexander is a story cinematic, not an Ark boss fight.'],
    'Save with Mogki in Lindblum’s guest room after the Alexandria aftermath gives control.', [35,55]],
  ['Setting Sail on the Blue Narciss', 'Lindblum / Black Mage Village',
    ['Check on Dagger and join the search for Cid’s three potion ingredients.', 'Complete the potion experiment and boarding preparations.', 'Take the Blue Narciss toward the Outer Continent.', 'Visit Black Mage Village and hear where the missing mages have gone.'],
    ['Travel encounters only. Review Dagger’s current condition and consider Eiko for reliable healing.', 'Skip world-wide side-quest tours and head for Kuja’s desert hideout.'],
    'Save with Mogryo in Black Mage Village after the new information, before sailing to the desert.', [40,60]],
  ['Kuja’s Bargain', 'Desert Palace / Forgotten Continent',
    ['Locate the correct desert sinkhole and enter Kuja’s trap.', 'Keep the prisoner scenes and the demand for the Gulug Stone.', 'Choose Zidane’s expedition with physical attackers; leave a functioning magic team behind.', 'Travel aboard the Hilda Garde I, then cross the Forgotten Continent to Oeilvert.'],
    ['Forgotten Continent encounters; reserve healing items for Oeilvert’s anti-magic field.', 'Suggested expedition: Zidane, Steiner, Freya, Amarant. Other choices work, but do not depend on spells inside.'],
    'Save with Mimoza outside Oeilvert; buy enough healing and revival items before entering.', [30,45]],
  ['Oeilvert and the Ark', 'Oeilvert',
    ['Enter the anti-magic ruins and activate the colored orb displays.', 'Follow the hologram sequence through the main rooms.', 'Listen to the stone faces and continue toward the Gulug Stone.', 'Win the guardian battle and keep the return transition.'],
    ['Ark: use physical attacks, item healing, and Clear Headed if available; avoid extended steal fishing.', 'Epitaph encounters: remove the original rather than letting copies overwhelm the team.'],
    'At the story transition to Cid in Desert Palace after obtaining the Gulug Stone. This is an editing boundary; retain the Oeilvert save and continue recording.', [35,55]],
  ['Escape the Desert Palace', 'Desert Palace',
    ['Complete Cid’s timed approach and balance puzzle.', 'Take the captive party through the candle and shadow puzzles.', 'Collect the Bloodstones encountered on the puzzle route to weaken the defense system.', 'Defeat the guardian, reunite the groups, and follow Kuja’s escape toward the Lost Continent.'],
    ['Valia Pira: remove Bloodstone enhancements before engaging; use the magic team’s strongest safe damage.', 'Palace random encounters; preserve MP for the guardian.'],
    'World map after escaping Desert Palace; summon Moguo and save before pursuing Kuja to Esto Gaza.', [45,65]],
  ['Into Mount Gulug', 'Esto Gaza / Mount Gulug / Lindblum',
    ['Restock at Esto Gaza and follow the route into Mount Gulug.', 'Navigate the rope and mining passages to the lower chambers.', 'Keep Eiko, Mog, and the twin jesters’ full confrontation.', 'Rescue Hilda and retain the return to Lindblum and Cid’s restoration.'],
    ['Red Dragon encounters; Meltigemini: cure Virus after the fight and protect the healer.', 'Do not miss the story’s forced summon moment by talking over it.'],
    'Save at Mogki in Lindblum after the rescue and restoration scenes; start the Hilda Garde III departure next episode.', [50,75]],
  ['Ipsen’s Upside-Down Castle', 'Hilda Garde III / Ipsen’s Castle',
    ['Keep Hilda’s briefing, Dagger’s resolve, and the airship launch.', 'Fly directly to Ipsen’s Castle with weak weapons retained for its reversed damage rule.', 'Navigate ladders and lifts to collect the four mirrors.', 'Defeat the guardian, then return inside to find Amarant and reunite the party.'],
    ['Taharka: use the castle’s weapon rule, heal through heavy hits, and do not overstay for steals.', 'Equip normal strong weapons again after leaving.'],
    'Outside Ipsen’s Castle after rescuing Amarant; use Moguo to save on the world map.', [40,60]],
  ['Four Shrines, One Gateway', 'Elemental shrines / Shimmering Island',
    ['Use the mirrors’ clues to visit the four shrine locations.', 'Drop off each pair and follow Zidane and Quina through the Earth Shrine traps.', 'Defeat the Earth Guardian and keep the parallel-party scenes.', 'Regroup aboard the airship and approach Shimmering Island.'],
    ['Earth Guardian: Float or earth protection helps if available; keep Quina alive for support.', 'The other shrine guardians are resolved in story scenes, not additional playable boss battles.'],
    'Save with Moguo on the world map before entering Shimmering Island; this preserves access to Gaia before Terra.', [30,45]],
  ['A Different World: Terra', 'Terra / Bran Bal',
    ['Enter Shimmering Island and keep the dimensional travel cinematic.', 'Follow the mysterious girl through Terra’s paths.', 'Reach Bran Bal and tour the Genome settlement.', 'Keep the party’s observations, Dagger’s reaction, and Zidane’s search for answers.'],
    ['Terra route encounters; take nearby equipment only.', 'No boss: use the quiet chapter to discuss identity and Vivi’s response without spoiling later revelations.'],
    'Save with Moorock in Bran Bal before following the route into Pandemonium.', [30,45]],
  ['You Are Not Alone', 'Pandemonium',
    ['Follow Garland into Pandemonium and retain the explanation of Zidane’s origins.', 'Play through Zidane’s isolation and each party member’s intervention.', 'Keep the complete You’re Not Alone sequence.', 'Regroup, heal, and establish the route into the palace mechanisms.'],
    ['Amdusias, Abadon, and Shell Dragon scripted encounters: let the party arrivals play out and heal once control allows.', 'Avoid inserting unrelated menu demonstrations over the central character sequence.'],
    'Save with Mozme in Pandemonium after the party reunites, before tackling the deeper machinery.', [30,45]],
  ['Garland, Kuja, and the Fall of Terra', 'Pandemonium / Invincible',
    ['Solve the timed light path, elevator settings, and teleporter route.', 'Recover at the final available moogle before the confrontation.', 'Fight the consecutive bosses and keep every conversation between them.', 'Escape Terra, rescue the Genomes, and watch the full end-of-disc sequence.'],
    ['Silver Dragon → Garland → Kuja: prepare for a consecutive sequence with strong healing and wind protection if owned.', 'Kuja’s ending is scripted; do not reset to avoid the cinematic outcome.'],
    'End-of-Disc-3 save prompt where available; otherwise stop at the Black Mage Village opening of Disc 4.', [50,75]],
  ['The Last Flight to Memoria', 'Black Mage Village / Invincible / Memoria entrance',
    ['Keep the Genomes’ arrival and the party’s final resolve.', 'Use available shops for a modest recovery-item restock; choose the final party from characters already developed.', 'Fly to the Iifa Tree and keep the allied fleet cinematic.', 'Defeat the entrance guardian and enter Memoria.'],
    ['Nova Dragon: keep group healing ready and use existing wind protection if available.', 'No Ozma, Hades, Chocobo grind, Friendly Monsters checklist, or rare equipment requirement.'],
    'Save at Memoria’s first glowing orb in the entrance hall after Nova Dragon.', [30,45]],
  ['Memoria: The Fire Guardian', 'Memoria / Stairs of Time / Recollection',
    ['Set the final party at the entrance orb and inspect nearby Kain’s Lance if useful.', 'Climb the Stairs of Time and follow Recollection’s platforms.', 'Pick up The Tower on the route if it improves Zidane’s equipment.', 'Defeat the fire guardian, then keep the memory of Alexandria.'],
    ['Maliris: equip Body Temp if learned; heal before the final blow because the death counter can punish a depleted party.', 'Memoria enemies are dangerous; retreat to the orb if supplies collapse.'],
    'Save at the hidden point on the central platform in The Past, beside the Angel Flute pickup after Maliris.', [20,35]],
  ['Memoria: The Wind Guardian', 'Memoria / The Past / Invincible memory',
    ['Resume at the hidden save point and continue through the shared memories.', 'Keep the discussion of memories the party did not personally experience.', 'Collect Rune Claws if using Amarant, then climb to the next guardian.', 'Defeat Tiamat and continue to the next resting alcove.'],
    ['Tiamat: protect against Confuse with Clear Headed; keep wind-resistant gear where available.', 'Use grounded party actions if airborne characters are being removed from the battle.'],
    'Save at the hidden point in the right-hand stair alcove in The Ruins, beyond Tiamat.', [20,35]],
  ['Memoria: The Water Guardian', 'Memoria / ruined city / ocean memory',
    ['Cross the ruined-city and sideways-path rooms toward the waterfall.', 'Use the visible save orb before the ocean section.', 'Keep Quina’s underwater moment; pass the optional Hades interaction without activating it.', 'Challenge Kraken and continue into the clock room.'],
    ['Kraken and tentacles: use water protection and Body Temp if available; keep healing stable while focusing targets.', 'Hades is intentionally outside this story-focused route.'],
    'Save at the hidden point in the right alcove at the bottom of Time Interval, immediately beyond Kraken.', [20,35]],
  ['Memoria: The Earth Guardian', 'Memoria / Time Interval / Gate to Space',
    ['Climb from the clock room and watch the memory of the world’s formation.', 'Take the ladder route and collect Mace of Zeus if using Vivi.', 'Approach the final guardian chamber.', 'Defeat Lich and hear the next part of Garland’s explanation.'],
    ['Lich: equip Locomotion against Stop and use Float or earth protection when practical; revive immediately after instant-death attacks.', 'Do not pursue Excalibur II’s speed requirement or phantom card matches.'],
    'Save at the hidden point on the left side of Gate to Space, after Lich and before entering the void.', [20,35]],
  ['Beyond Memory: The Crystal World', 'Memoria void / Crystal World',
    ['Leave the final guardian room and move through the void.', 'Keep Garland’s final explanation and the transition to the crystal landscape.', 'Follow the crystal paths toward Kuja without detouring back to optional quests.', 'Recover at the last save point and assign healing, revival, and damage roles.'],
    ['Crystal versions of earlier guardians can appear as random encounters; escape if resources become unsafe.', 'No required boss this part. Keep the journey concise rather than farming levels to fill time.'],
    'Save at the Crystal World’s final glowing orb before entering the encounter area leading to Kuja.', [15,25]],
  ['Deathguise: The Last Gatekeeper', 'Crystal World',
    ['Resume at the final orb and begin at full HP with revival items available.', 'Approach Kuja to trigger Deathguise.', 'Win the fight, then return to the previous room instead of advancing again.', 'Recover and preserve a separate final-boss save.'],
    ['Deathguise: prepare for the opening Meteor damage; prioritize stabilizing the party before committing to attacks.', 'A short successful fight is enough; do not manufacture extra attempts to hit the target runtime.'],
    'Save again at the Crystal World’s final orb after Deathguise, before re-approaching Kuja.', [15,25]],
  ['Trance Kuja: Everything on the Line', 'Crystal World / final battle transition',
    ['Load the post-Deathguise save and check status protection for the following battle too.', 'Approach Kuja and retain the entire confrontation.', 'Defeat Trance Kuja and keep the Ultima cinematic.', 'Carry the recording into the transition so no ending dialogue is lost.'],
    ['Trance Kuja: recover after Flare Star and maintain a dedicated healer; avoid long optional steal attempts.', 'This leads directly toward Necron; there is no normal save between the final bosses.'],
    'Editing boundary after Kuja’s Ultima and before the Necron confrontation. Record Parts 43–45 continuously; do not quit here expecting a save.', [15,30]],
  ['Necron: Choosing to Live', 'Hill of Despair / Iifa Tree aftermath',
    ['Resume the uninterrupted final sequence and keep Necron’s introduction.', 'Select and prepare the final battle party when prompted.', 'Win the last battle and watch the escape from the collapsing tree.', 'Keep Zidane’s decision to return for Kuja and their final exchange.'],
    ['Necron: prepare several status immunities; recover from Grand Cross before attacking again. Keep more than one revival option available.', 'No save or free-roam cleanup after victory.'],
    'Editing boundary at the transition from the Iifa Tree resolution to the later epilogue. Keep the same continuous recording running for Part 45.', [20,35]],
  ['A Place to Call Home: The Ending', 'Epilogue / Alexandria / credits',
    ['Watch the full character epilogue and all closing letters.', 'Keep the return to Alexandria and the performance of I Want to Be Your Canary.', 'Let the reunion and final cinematics play without interruption.', 'Include the credits and a brief reflection after the ending music.'],
    ['No combat. This is the narrative finale, not an optional-boss cleanup episode.', 'Do not replace ending scenes with a recap.'],
    'The final The End screen after all credits; stop recording after the closing reflection.', [20,35]]
].map((row, index) => ({
  episodeNumber: index + 1,
  gameId: 'ff9',
  suggestedTitle: row[0],
  arcOrAct: index < 11 ? 'Disc 1' : index < 23 ? 'Disc 2' : index < 35 ? 'Disc 3' : 'Disc 4',
  location: row[1], storyBeats: row[2], keyEncountersOrActivities: row[3], stoppingPoint: row[4],
  estimatedMinutes: row[5],
  runtimeNote: 'Target: 30–40 minutes. These editorial estimates include story scenes and commentary at normal speed. Dense chapters can run longer; Disc 4 is deliberately divided into shorter parts to preserve the requested 36–45 band without grinding. Transition stops are editing cuts, not new save points.'
}));
