'use strict';
// Activity order is deterministic: sort currently unlocked map markers north to
// south. Count unique completed icons, not replays. District quotas use the game's
// chapter-specific map, so crimes never leak between the three DLC campaigns.
const SPIDERMAN_EPISODES = [
  ['The Black Cat Returns', 'The Heist', 'Manhattan Museum / surrounding streets',
    ['Select The Heist from the DLC menu on your existing story save.', 'Complete The Maria: investigate the museum, follow the security evidence, and stop thieves escaping with art.', 'Keep Felicia’s reveal and the post-mission calls.', 'Complete The Trouble with Arson to introduce the chapter’s Maggia crimes; open the map and note each district with a crime counter.'],
    ['Museum combat: prioritize marked escaping thieves over stationary enemies.', 'Maggia crime introduction. Begin a north-to-south list of eligible districts in production notes; a district is finished only when its counter reaches 5/5.'],
    'After The Trouble with Arson completes and free roam returns, wait for autosave, then create a manual save before Long Lost Loot.'],
  ['Walter Hardy’s Missing Art', 'The Heist', 'Long Lost Loot / northern art-marker route',
    ['Complete Long Lost Loot and keep Detective Mackey’s introduction.', 'Collect the introductory art stash, then the next three uncollected art markers working north to south: cumulative target 4/10.', 'Let each collectible conversation finish before starting another activity.', 'Finish the northernmost eligible district’s Maggia counter; log its name and 5/5 result.'],
    ['Hardy’s Stolen Art: 4/10 total, counting the tutorial pickup once.', 'Maggia crimes: first eligible district 5/5. Use scanning while traveling; remove empty waiting time from the edit.'],
    'On a safe rooftop after art pickup four and the first district’s 5/5 map check; manual save before Like Old Times.'],
  ['Like Old Times, New Trouble', 'The Heist', 'Black Cat mission route / Screwball introduction',
    ['Complete Like Old Times and keep the developing Peter–Felicia story.', 'Complete Something is Screwy to reveal the challenge set.', 'Clear the two northernmost unfinished Screwball challenge icons.', 'Collect the next two art stashes, reaching 6/10; clear the next eligible crime district to 5/5.'],
    ['Screwball challenges 1–2 of 5: aim for Spectacular or better; use Photobomb opportunities shown by the HUD.', 'Art 6/10; second eligible district crime counter 5/5. Ratings are separate from basic map completion.'],
    'Free roam after the second challenge results screen and the district/art audit; manual save before Trail of the Cat.'],
  ['On the Trail of the Cat', 'The Heist', 'Trail of the Cat / Pursuing the Truth',
    ['Complete Trail of the Cat, following the investigation and traversal prompts.', 'Complete Pursuing the Truth and retain the entire Black Cat chase.', 'Collect the next two unfinished art icons, reaching 8/10.', 'Clear the third Screwball icon in the north-to-south order and finish the next unfinished crime district.'],
    ['Black Cat chase: prioritize clean traversal and reacquiring the route over risky shortcuts.', 'Challenge 3/5 at Spectacular+; art 8/10; third crime district 5/5.'],
    'After Pursuing the Truth and the scheduled activities are complete, manual save in free roam before Newsflash.'],
  ['Newsflash and the Long Con', 'The Heist', 'MJ investigation / police precinct / remaining art route',
    ['Complete Newsflash and let MJ’s investigation scenes play in full.', 'Collect the final two art stashes for 10/10; wait for the follow-up call.', 'Complete Like a Fiddle at the precinct to close Walter Hardy’s story.', 'Clear challenge four and finish the next eligible crime district’s remaining counter.'],
    ['MJ stealth: observe patrols and use distractions instead of sprinting through sightlines.', 'All 10 art stashes and Like a Fiddle; Screwball 4/5 at Spectacular+; next crime district 5/5.'],
    'Free roam after Like a Fiddle completes and the fourth challenge results have been recorded; manual save before Cover for the Cat.'],
  ['Cover for the Cat', 'The Heist', 'Black Cat team-up / city activity sweep',
    ['Complete Cover for the Cat and keep the team-up dialogue.', 'Finish the fifth unique Screwball challenge; revisit only icons below Spectacular if pursuing all DLC trophies.', 'Sweep every remaining district with a Maggia counter until each displays 5/5; use the chapter map to catch districts outside the earlier route.', 'Audit art 10/10, Like a Fiddle complete, and five completed challenges before the finale.'],
    ['Team-up combat and stealth with Felicia; exploit isolated targets before alarms.', 'Screwball 5/5 at Spectacular+ and all chapter Maggia crime counters full. Carry unfinished spawn-dependent work into Part 7 if necessary.'],
    'Manual save in free roam after Cover for the Cat and the activity audit, before Follow the Money.'],
  ['The Heist Finale: Follow the Money', 'The Heist', 'Hammerhead operation / Felicia’s hideout',
    ['Complete Follow the Money and keep the entire ending and follow-up calls.', 'Resolve any remaining chapter activity counter flagged in Part 6.', 'Open each district panel and the DLC menu to confirm The Heist is 100%.', 'Show the completion rewards and a short chapter reflection; only then switch chapters next episode.'],
    ['Final Maggia combat and the story’s escape sequence; prioritize ranged threats and preserve Focus for healing.', 'Completion gate: story finished, 10 art, Like a Fiddle, five challenges, every Maggia crime counter full, chapter 100%.'],
    'The Heist 100% completion shown in the DLC/menu overview; return to free roam and manual save before selecting Turf Wars.'],
  ['Turf Wars: Blindsided', 'Turf Wars', 'Harlem Sanitarium / The Bar With No Name',
    ['Switch to Turf Wars; its map counters start independently from The Heist.', 'Complete Blindsided, from the exterior assault to the interior investigation.', 'Keep Yuri’s full confrontation and the aftermath.', 'Complete The Bar With No Name, including the Spider-Bot investigation, to reveal Hammerhead’s fronts.'],
    ['Sanitarium enemies with stolen Sable equipment: prioritize guns and use dodge-under attacks against shields.', 'Record all four Hammerhead Front markers and the chapter’s eligible crime districts.'],
    'After The Bar With No Name mission-complete screen and return to free roam; manual save before Jury Rigging.'],
  ['Hammerhead’s Expanding Empire', 'Turf Wars', 'Jury Rigging / Last Stand / first Front',
    ['Complete Jury Rigging, following the surveillance and interception objectives.', 'Complete Last Stand and preserve its Yuri story beat.', 'Clear the northernmost unfinished Hammerhead Front through all waves.', 'Patrol the northernmost district with a Hammerhead crime counter until it reaches 5/5.'],
    ['Hammerhead Front 1/4: remove launchers early and use aerial combat to reduce crowd pressure.', 'First of four eligible crime districts 5/5. Base bonus objectives can be attempted naturally; a completed base icon is the completion requirement.'],
    'After Front one’s results and the district’s 5/5 map check; manual save in free roam before Season Two.'],
  ['Screwball’s Second Season', 'Turf Wars', 'Season Two / challenge circuit / second Front',
    ['Complete Season Two to open the chapter’s five challenges.', 'Clear the first two challenge icons working north to south.', 'Clear the next unfinished Hammerhead Front through its final wave.', 'Fill the second eligible district’s Hammerhead crime counter.'],
    ['Screwball challenges 1–2/5 at Spectacular+; read gadget restrictions before starting.', 'Hammerhead Fronts 2/4; crime districts 2/4 at 5/5.'],
    'Free roam after Front two and the two challenge results; manual save before Lockup.'],
  ['Lockup Under Siege', 'Turf Wars', 'Police lockup / third Front / challenge route',
    ['Complete Lockup and keep the whole assault and aftermath.', 'Clear the third unfinished Hammerhead Front.', 'Complete challenges three and four in the established map order.', 'Finish the third eligible district’s Hammerhead crimes; note any remaining spawns for the next patrol.'],
    ['Lockup defense: deal with ranged attackers and protect health before pursuing combo score.', 'Fronts 3/4, challenges 4/5 at Spectacular+, crime districts 3/4 complete.'],
    'Manual save after Lockup, Front three, and the activity results; stop in free roam before Yuri’s Revenge.'],
  ['Yuri’s Revenge and Season Finale', 'Turf Wars', 'Yuri investigation / final Front / Screwball event',
    ['Complete Yuri’s Revenge and retain the investigation’s conclusion.', 'Clear the fourth Hammerhead Front and the fifth Screwball challenge.', 'Follow Screwball’s subsequent call and complete Season Finale once available.', 'Finish the fourth eligible crime district and audit every chapter district counter.'],
    ['All four Fronts; all five challenges at Spectacular+; Season Finale side mission.', 'All four Hammerhead crime districts 5/5. If a follow-up call is delayed, allow free roam and complete it before leaving this chapter.'],
    'Free-roam manual save after Season Finale and the activity audit, before Bring the Hammer Down.'],
  ['Bring the Hammer Down', 'Turf Wars', 'Hammerhead showdown / Manhattan',
    ['Complete Bring the Hammer Down, including the boss encounter and full ending.', 'Keep Yuri’s final chapter scenes and subsequent calls.', 'Resolve any outstanding activity counter or Season Finale follow-up before changing DLC.', 'Show Turf Wars at 100% and its completion rewards.'],
    ['Hammerhead boss: dodge his charge, exploit recovery windows, and use the arena opportunities the fight presents.', 'Completion gate: all eight main missions, four Fronts, five challenges, Season Finale, all crime counters, chapter 100%.'],
    'Turf Wars 100% visible in the DLC overview; manual save in free roam before selecting Silver Lining.'],
  ['Silver Sable Returns', 'Silver Lining', 'Old Friends / Season 3',
    ['Select Silver Lining and introduce the chapter’s fresh map counters.', 'Complete Old Friends and keep the reunion with Silver Sable.', 'Complete Season 3 and reveal the final five Screwball challenges.', 'Clear the first two challenge icons north to south; begin the northernmost eligible crime district.'],
    ['Sable confrontation and upgraded Hammerhead enemies; use aerial positioning against jetpack threats.', 'Screwball 2/5 at Spectacular+; log crime progress by district rather than counting repeated events.'],
    'Free roam after Season 3 and two challenge results; manual save before Rio Bravo.'],
  ['An Uneasy Partnership', 'Silver Lining', 'Rio Bravo / Together But Alone / Humanitarian Aid',
    ['Complete Rio Bravo and retain the next lead in the pursuit.', 'Complete Together But Alone, following the moving targets and Sable’s intervention.', 'Complete Humanitarian Aid and meet David Obademi.', 'Finish the northernmost eligible district’s crime counter and complete challenge three.'],
    ['Convoy pursuit and Hammerhead thugs: keep the objective vehicle in view and use mission prompts to advance each stage.', 'Challenge 3/5 at Spectacular+; first eligible crime district 5/5.'],
    'After Humanitarian Aid and the patrol/challenge results, manual save before Trust Issues.'],
  ['Trust Issues and Project Olympus', 'Silver Lining', 'Trust Issues / Greenwich Olympus Hideout',
    ['Complete Trust Issues and keep Peter and Sable’s developing alliance.', 'Check the newly available Olympus Hideout icons.', 'Clear the Greenwich Olympus Hideout through all waves and listen to the supply-related dialogue.', 'Clear the fourth Screwball challenge and finish the next eligible crime district.'],
    ['Olympus Hideouts 1/3: manage heavy enemies with gadgets and reserve Focus for emergency healing.', 'Challenge 4/5 at Spectacular+; continue the north-to-south district crime ledger.'],
    'Free roam after Greenwich’s hideout completion and challenge four; manual save before Getting Deep.'],
  ['Getting Deep: Yuri’s Trail', 'Silver Lining', 'Getting Deep / Chinatown Olympus Hideout / recording trail',
    ['Complete Getting Deep and keep its full discoveries and rescue sequence.', 'Follow the crime-scene introduction once it becomes available; collect three recordings total, including any introductory pickup.', 'Clear the Chinatown Olympus Hideout and retain the associated calls.', 'Complete challenge five, then follow the Screwball call and complete Wrap Party.'],
    ['Olympus Hideouts 2/3; crime-scene recordings 3/9, using the collectible counter to avoid double-counting.', 'All five challenges at Spectacular+; Wrap Party chase. Let delayed follow-up calls resolve before the next story mission.'],
    'Free-roam manual save after Wrap Party and the Chinatown hideout; leave One Plus One Equals Win unstarted.'],
  ['Aiding a Human', 'Silver Lining', 'Midtown Olympus Hideout / Financial District docks',
    ['Clear the Midtown Olympus Hideout, completing all three bases.', 'Answer David’s follow-up call and complete Aiding a Human at the docks.', 'Collect the next three uncollected crime-scene recordings in north-to-south order, reaching 6/9.', 'Patrol the next unfinished crime district until its counter is full.'],
    ['All three Olympus Hideouts plus Aiding a Human; keep the supply recovery conclusion.', 'Crime-scene recordings 6/9. Return to district panels after crimes so completed districts do not absorb the patrol budget.'],
    'After Aiding a Human’s completion and six recordings confirmed, manual save in free roam.'],
  ['Scales of Justice', 'Silver Lining', 'Remaining crime scenes / Manhattan districts',
    ['Collect the final three recordings for 9/9, retaining the audio and Peter’s reactions.', 'Follow the unlocked lead and complete Scales of Justice.', 'Fill every remaining Silver Lining crime counter; audit all district panels, including districts outside the route.', 'Check Wrap Party, Aiding a Human, and Scales of Justice complete; verify three hideouts and five challenges before the finale.'],
    ['All nine recordings and Scales of Justice: this storyline is mandatory for the chapter’s 100% scope.', 'Finish all crime counters; revisit below-Spectacular challenges for trophies if needed. Ultimate scores are not required.'],
    'Manual save in free roam after Scales of Justice and all available side content, immediately before One Plus One Equals Win.'],
  ['Hammerhead’s Last Stand: 100% Finale', 'Silver Lining', 'Sable’s hideout / final Hammerhead battle',
    ['Begin One Plus One Equals Win and keep the alliance’s final setup.', 'Defeat the enhanced Hammerhead through all phases, including the Sable team-up prompts.', 'Watch the complete ending and follow-up scenes.', 'Resolve any missed counter from the audit, then show each DLC chapter’s individual 100% in the menu; retain separate chapter completion saves.'],
    ['Final Hammerhead mech battle: evade area attacks, use the provided stun opportunities, and follow Sable’s coordinated openings.', 'Final gate: The Heist 100%, Turf Wars 100%, Silver Lining 100%; 15 unique challenges at Spectacular+ for the three challenge trophies.'],
    'After the final ending and all three chapter completion readouts show 100%; return to Silver Lining free roam, manual save, then end the series.']
].map((row, index) => ({
  episodeNumber: index + 1, gameId: 'spiderman-ctns', suggestedTitle: row[0],
  arcOrAct: row[1], location: row[2], storyBeats: row[3],
  keyEncountersOrActivities: row[4], stoppingPoint: row[5], estimatedMinutes: [25,35],
  runtimeNote: 'Target edited video: 25–35 minutes including cutscenes. Crime spawns, challenge retries, and multi-activity chapters can need 40–75+ minutes to record. Trim empty travel and repeat attempts; keep first clears and story scenes. Carry overflow within the same chapter, but do not leave its finale below 100%. North-to-south means order by icon position on your current chapter map.'
}));
